# Goal: supervisor request correlated to one immutable snapshot.
uint8 MODE_SHADOW=2
uint8 MODE_LEARNED=3

uint16 protocol_version
uint8[16] request_uuid
uint8[16] snapshot_uuid
uint64 episode_id
uint64 decision_epoch
uint64 map_revision
uint64 target_revision
int64 requested_at_ns
int64 deadline_ns
uint8 requested_mode
uint8[32] snapshot_payload_sha256
uint8[32] checkpoint_allowlist_sha256
---
# Result: proposal only; never an application authorization.
uint8 RESULT_OK=0
uint8 RESULT_SNAPSHOT_MISSING=1
uint8 RESULT_SNAPSHOT_MISMATCH=2
uint8 RESULT_STALE=3
uint8 RESULT_DEADLINE=4
uint8 RESULT_RUNNER_RESTART=5
uint8 RESULT_PROTOCOL=6
uint8 RESULT_MODEL_ERROR=7
uint8 RESULT_CANCELED=8

uint8 result_code
uint8[16] request_uuid
uint8[16] snapshot_uuid
uint64 episode_id
uint64 decision_epoch
uint64 map_revision
uint64 target_revision
int64 produced_at_ns
uint32 runner_generation
uint64 reset_counter
float32[7] proposal_external_deg
uint8[32] checkpoint_sha256
uint8[32] proposal_payload_sha256
string<=128 reason
---
# Feedback is bounded by contract to at most 4 Hz.
uint8 PHASE_VALIDATING=0
uint8 PHASE_RESETTING=1
uint8 PHASE_INFERRING=2

uint8 phase
uint32 runner_generation
uint64 reset_counter
int64 stamp_ns
